# Generated by Django 3.1.2 on 2020-10-12 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcatalogue',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
